---
title: "Project 4"
author: "Team 4"
output:
  pdf_document: default
  word_document: default
---

## Step 0: Load the packages, specify directories
```{r, warning=FALSE}
start.time0 <- Sys.time()
if (!require("lda")) install.packages("lda")
library(lda)
source("../lib/cleandata.R")
source("../lib/evaluation_measures.R")
```

## Step 1: Clean all the data and do the preparation work to run LDA and hclust
```{r}
# set up the corpus of each document
corpus<- function(llist){
  document<- function(lllist) {
    words_apperance <- c(unlist(strsplit(lllist[[4]], " ")), unlist(strsplit(lllist[[5]], " ")))
    name_appearance <- unlist(lllist[[3]])
    doc <- list(words = words_apperance, name = name_appearance)
    return(doc)
  }
  return(lapply(llist, document))
}
doc_corpus<- lapply(data_list, corpus)

# extract all words(coauthor names, title of the paper and published journal of each documentation)
allwords_fun<- function(llist) {
  allwords_fun1<- function(lllist) {
    return(c(lllist$name, lllist$words))
  }
  return(lapply(llist, allwords_fun1))
}
doc_allwords<- lapply(doc_corpus, allwords_fun)

# the vocab(all words) used in the documents of each name)
vocab_fun<- function(llist) {
  vocab<- c()
  n<- length(llist)
  for(i in 1:n){
    vocab<- c(vocab,llist[[i]])
  }
  vocab<- unique(vocab)
  return(vocab)
}
vocab<- lapply(doc_allwords, vocab_fun)

# extract the Gold standard clusters for each author name
query.g<- function(llist){
  gold<- function(lllist) {
    gold_id<- lllist[[1]]
    return(gold_id)
  }
  return(sapply(llist, gold))
}
gold_mat<- sapply(data_list, query.g)

# construct the list format we should use in the code
index<- function(x,a) {return(which(a==x))}
doc_format<- vector("list", 14)
for(i in 1:14) {
  format_fun<- function(lllist) {
    t<- table(lllist)
    vec1<- as.numeric(sapply(names(t), index, a=vocab[[i]]))-1
    vec2<- as.numeric(t)
    m<- matrix(as.integer(c(vec1, vec2)), ncol = 2)
    return(t(m))
  }
  doc_format[[i]] <- lapply(doc_allwords[[i]], format_fun)
}
names(doc_format)<- query.list
```

## Run LDA 
```{r, warning=FALSE}
# main function to run LDA model and tune the parameter
# Input: list_num: the index of the each list, for example: list_num = 1 represents the author name is "A Gupta"
#        topic_num: the parameter used in LDA
main <- function(list_num, topic_num) {
  start.time <- Sys.time()
  k<- topic_num
  # parameter values
  beta <- 0.01
  alpha <- k/50
  
  # run the LDA
  runlda <- lda.collapsed.gibbs.sampler(doc_format[[list_num]],
                                        k, vocab[[list_num]],
                                        num.iterations = 1000,
                                        alpha = alpha, eta = beta)

  # Calculate topic-word matrix
  hw <- runlda$topics
  W <- length(vocab[[list_num]])
  sum_h <- rowSums(hw)
  matrix_sumh <- matrix(rep(sum_h,k),nrow=k,ncol=W)
  phi <- (hw+beta)/(matrix_sumh+W*beta)

  # Calculate topic-document probability matrix
  hd <- runlda$document_sums
  D <- length(doc_format[[list_num]])
  sum_hd <- colSums(hd)
  matrix_sumhd <- matrix(rep(sum_hd,each=k),nrow=k,ncol=D)
  theta <- (hd+alpha)/(matrix_sumhd+k*alpha)
  colnames(theta) <- c(1:ncol(theta))
  distance<- dist(data.frame(t(theta)))

  # Agglomerative Clustering
  clust.num<- max(gold_mat[[list_num]])
  hcluster <- hclust(distance, "complete")
  hclust_id<- cutree(hcluster, gold_mat[[list_num]])
  
  # compute accuracy based on precision anf recall
  match_mat<- matching_matrix(gold_mat[[list_num]], hclust_id)
  perform<- performance_statistics(match_mat)
  end.time <- Sys.time()
  return(c(unlist(perform), cluster.time = end.time- start.time))
}
```

## Tune the parameter topic number to get the best result
```{r, warning=FALSE}
# tune the parameter(topic number) to get the max accuracy
# the best topic number is either 5 or 10 based on the paper
tune <- function(list_num) {
  start.time <- Sys.time()
  k_vec<- c(5, 10)
  perform_mat <- sapply(k_vec ,main, list_num = list_num)
  acc_vec <- perform_mat[4,]
  best_ind <- which.max(acc_vec)
  best_k <- k_vec[best_ind]
  end.time <- Sys.time()
  return(c(best.k = best_k, perform_mat[,best_ind], 
           tune.time = end.time - start.time))
}
```

## Final results for each author names
```{r, warning=FALSE}
# final results
final_result<- sapply(1:14, tune)
colnames(final_result)<- query.list
final_result
end.time0<- Sys.time()

# the whole time to complete our algorithm on Name Disambiguation
end.time0 - start.time0
```